# Generated by Django 4.0.4 on 2022-04-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealler_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dealist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('st', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('zip', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('short_name', models.CharField(max_length=60)),
                ('full_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='mytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dealership', models.IntegerField()),
                ('review', models.CharField(max_length=60)),
                ('purchase', models.CharField(max_length=60)),
                ('purchase_date', models.DateField()),
                ('car_make', models.CharField(max_length=60)),
                ('car_model', models.CharField(max_length=60)),
                ('car_year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='dealler',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
